substitutions:
  _REGION: us-central1
  _AR_REPOSITORY: orbit
  _SERVICE_NAME: orbit-api
  _ALLOW_UNAUTHENTICATED: "true"
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "10"
  _CPU: "1"
  _MEMORY: 1Gi
  _TIMEOUT_SECONDS: "300"
  _CLOUDSQL_INSTANCE: ""
  _DB_URL_SECRET_NAME: orbit-db-url
  _DB_URL_SECRET_VERSION: latest
  _JWT_SECRET_NAME: orbit-jwt-secret
  _JWT_SECRET_VERSION: latest
  _ORBIT_ENV: production
  _ORBIT_JWT_ISSUER: orbit
  _ORBIT_JWT_AUDIENCE: orbit-api
  _ORBIT_JWT_ALGORITHM: HS256
  _ORBIT_RATE_LIMIT_EVENTS_PER_MONTH: "10000"
  _ORBIT_RATE_LIMIT_QUERIES_PER_MONTH: "50000"
  _ORBIT_RATE_LIMIT_FREE_API_KEYS: "3"
  _ORBIT_RATE_LIMIT_FREE_RETENTION_DAYS: "30"
  _ORBIT_RATE_LIMIT_PILOT_PRO_EVENTS_PER_MONTH: "250000"
  _ORBIT_RATE_LIMIT_PILOT_PRO_QUERIES_PER_MONTH: "1000000"
  _ORBIT_RATE_LIMIT_PILOT_PRO_API_KEYS: "25"
  _ORBIT_RATE_LIMIT_PILOT_PRO_RETENTION_DAYS: "180"
  _ORBIT_PILOT_PRO_ACCOUNT_KEYS: ""
  _ORBIT_USAGE_WARNING_THRESHOLD_PERCENT: "80"
  _ORBIT_USAGE_CRITICAL_THRESHOLD_PERCENT: "95"
  _ORBIT_RATE_LIMIT_PER_MINUTE: 300/minute
  _ORBIT_MAX_INGEST_CONTENT_CHARS: "20000"
  _ORBIT_MAX_QUERY_CHARS: "2000"
  _ORBIT_MAX_BATCH_ITEMS: "100"
  _ORBIT_CORS_ALLOW_ORIGINS: https://your-frontend.vercel.app
  _ORBIT_OTEL_SERVICE_NAME: orbit-api
  _ORBIT_OTEL_EXPORTER_ENDPOINT: ""

steps:
  - id: build-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:${BUILD_ID}
      - .

  - id: push-image
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:${BUILD_ID}

  - id: deploy-cloud-run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    env:
      - PROJECT_ID=$PROJECT_ID
      - REGION=${_REGION}
      - SERVICE_NAME=${_SERVICE_NAME}
      - IMAGE_URI=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:${BUILD_ID}
      - ALLOW_UNAUTHENTICATED=${_ALLOW_UNAUTHENTICATED}
      - MIN_INSTANCES=${_MIN_INSTANCES}
      - MAX_INSTANCES=${_MAX_INSTANCES}
      - CPU=${_CPU}
      - MEMORY=${_MEMORY}
      - TIMEOUT_SECONDS=${_TIMEOUT_SECONDS}
      - CLOUDSQL_INSTANCE=${_CLOUDSQL_INSTANCE}
      - DB_URL_SECRET_NAME=${_DB_URL_SECRET_NAME}
      - DB_URL_SECRET_VERSION=${_DB_URL_SECRET_VERSION}
      - JWT_SECRET_NAME=${_JWT_SECRET_NAME}
      - JWT_SECRET_VERSION=${_JWT_SECRET_VERSION}
      - ORBIT_ENV=${_ORBIT_ENV}
      - ORBIT_JWT_ISSUER=${_ORBIT_JWT_ISSUER}
      - ORBIT_JWT_AUDIENCE=${_ORBIT_JWT_AUDIENCE}
      - ORBIT_JWT_ALGORITHM=${_ORBIT_JWT_ALGORITHM}
      - ORBIT_RATE_LIMIT_EVENTS_PER_MONTH=${_ORBIT_RATE_LIMIT_EVENTS_PER_MONTH}
      - ORBIT_RATE_LIMIT_QUERIES_PER_MONTH=${_ORBIT_RATE_LIMIT_QUERIES_PER_MONTH}
      - ORBIT_RATE_LIMIT_FREE_API_KEYS=${_ORBIT_RATE_LIMIT_FREE_API_KEYS}
      - ORBIT_RATE_LIMIT_FREE_RETENTION_DAYS=${_ORBIT_RATE_LIMIT_FREE_RETENTION_DAYS}
      - ORBIT_RATE_LIMIT_PILOT_PRO_EVENTS_PER_MONTH=${_ORBIT_RATE_LIMIT_PILOT_PRO_EVENTS_PER_MONTH}
      - ORBIT_RATE_LIMIT_PILOT_PRO_QUERIES_PER_MONTH=${_ORBIT_RATE_LIMIT_PILOT_PRO_QUERIES_PER_MONTH}
      - ORBIT_RATE_LIMIT_PILOT_PRO_API_KEYS=${_ORBIT_RATE_LIMIT_PILOT_PRO_API_KEYS}
      - ORBIT_RATE_LIMIT_PILOT_PRO_RETENTION_DAYS=${_ORBIT_RATE_LIMIT_PILOT_PRO_RETENTION_DAYS}
      - ORBIT_PILOT_PRO_ACCOUNT_KEYS=${_ORBIT_PILOT_PRO_ACCOUNT_KEYS}
      - ORBIT_USAGE_WARNING_THRESHOLD_PERCENT=${_ORBIT_USAGE_WARNING_THRESHOLD_PERCENT}
      - ORBIT_USAGE_CRITICAL_THRESHOLD_PERCENT=${_ORBIT_USAGE_CRITICAL_THRESHOLD_PERCENT}
      - ORBIT_RATE_LIMIT_PER_MINUTE=${_ORBIT_RATE_LIMIT_PER_MINUTE}
      - ORBIT_MAX_INGEST_CONTENT_CHARS=${_ORBIT_MAX_INGEST_CONTENT_CHARS}
      - ORBIT_MAX_QUERY_CHARS=${_ORBIT_MAX_QUERY_CHARS}
      - ORBIT_MAX_BATCH_ITEMS=${_ORBIT_MAX_BATCH_ITEMS}
      - ORBIT_CORS_ALLOW_ORIGINS=${_ORBIT_CORS_ALLOW_ORIGINS}
      - ORBIT_OTEL_SERVICE_NAME=${_ORBIT_OTEL_SERVICE_NAME}
      - ORBIT_OTEL_EXPORTER_ENDPOINT=${_ORBIT_OTEL_EXPORTER_ENDPOINT}
    args:
      - -c
      - |
        bash scripts/deploy_gcp_cloud_run.sh

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:${BUILD_ID}

options:
  logging: CLOUD_LOGGING_ONLY
